#!/bin/bash
# =============================================================================
# hpc/setup_env.sh  --  Bootstrap the QuESt Planning Python environment on HPC
# =============================================================================
# Run this ONCE on the cluster login node before submitting any jobs.
#
# Usage:
#   bash hpc/setup_env.sh [--repo-path /path/to/quest_planning_repo]
#
# What this script does:
#   1. Creates a conda environment named 'quest_planning' with Python 3.11.
#   2. Installs all Python dependencies from requirements.txt (including the
#      scikit-learn fix added in this branch).
#   3. Installs the quest_planning package itself in editable mode.
#   4. Verifies that the key imports work (no solver required).
#
# Prerequisites:
#   - conda or miniconda/micromamba available on the login node.
#   - Access to the QuESt Planning git repository (this repo).
#   - Gurobi installed separately (via cluster module or site license).
#     The Python gurobipy package is installed here but Gurobi itself must
#     be available at job runtime via modules.sh.
#
# After running this script, edit hpc/modules.sh (generated by study_builder.py
# when you run it for the first time) to activate this environment in each job.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
REPO_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo-path)
            REPO_PATH="$2"
            shift 2
            ;;
        *)
            echo "Unknown argument: $1" >&2
            exit 1
            ;;
    esac
done

ENV_NAME="quest_planning"
PYTHON_VERSION="3.11"

echo "============================================================"
echo "QuESt Planning HPC Environment Setup"
echo "Repository : $REPO_PATH"
echo "Conda env  : $ENV_NAME (Python $PYTHON_VERSION)"
echo "============================================================"

# ---------------------------------------------------------------------------
# 1. Detect conda / micromamba
# ---------------------------------------------------------------------------
if command -v micromamba &>/dev/null; then
    CONDA_CMD="micromamba"
elif command -v conda &>/dev/null; then
    CONDA_CMD="conda"
else
    echo "ERROR: Neither 'conda' nor 'micromamba' found in PATH."
    echo "       Load a conda/anaconda module first, e.g.:"
    echo "         module load anaconda3"
    echo "       Then re-run this script."
    exit 1
fi
echo "Using: $CONDA_CMD"

# ---------------------------------------------------------------------------
# 2. Create environment (skip if already exists)
# ---------------------------------------------------------------------------
if $CONDA_CMD env list | grep -q "^${ENV_NAME} "; then
    echo "Environment '$ENV_NAME' already exists — skipping creation."
else
    echo "Creating conda environment '$ENV_NAME' ..."
    $CONDA_CMD create -n "$ENV_NAME" python="$PYTHON_VERSION" -y
fi

# ---------------------------------------------------------------------------
# 3. Activate and install dependencies
# ---------------------------------------------------------------------------
# Activation syntax differs slightly between conda and micromamba.
if [[ "$CONDA_CMD" == "micromamba" ]]; then
    eval "$(micromamba shell hook --shell bash)"
    micromamba activate "$ENV_NAME"
else
    # Source conda's shell functions so 'conda activate' works in a script.
    CONDA_BASE=$(conda info --base)
    source "${CONDA_BASE}/etc/profile.d/conda.sh"
    conda activate "$ENV_NAME"
fi

echo "Installing dependencies from requirements.txt ..."
pip install --upgrade pip
pip install -r "${REPO_PATH}/requirements.txt"

# ---------------------------------------------------------------------------
# 4. Install the quest_planning package in editable mode
# ---------------------------------------------------------------------------
echo "Installing quest_planning package (editable) ..."
pip install -e "${REPO_PATH}"

# ---------------------------------------------------------------------------
# 5. Quick import verification (no solver required)
# ---------------------------------------------------------------------------
echo ""
echo "Verifying key imports ..."
python - <<'PYCHECK'
import sys
failures = []

checks = [
    ("yaml",                         "PyYAML"),
    ("pandas",                       "pandas"),
    ("numpy",                        "numpy"),
    ("pyomo.environ",                "Pyomo"),
    ("sklearn.cluster",              "scikit-learn"),
    ("quest_planning.explan_simulation", "quest_planning"),
    ("quest_planning.explan.explan_data_handler", "ExplanDataHandler"),
    ("quest_planning.explan.explan_optimizer",    "ExplanOptimizer"),
    ("quest_planning.explan.explan_results_viewer","ExplanResultsViewer"),
]

for module, label in checks:
    try:
        __import__(module)
        print(f"  OK  {label} ({module})")
    except ImportError as e:
        print(f"  FAIL {label} ({module}): {e}")
        failures.append(module)

if failures:
    print(f"\nFAILED imports: {failures}")
    sys.exit(1)
else:
    print("\nAll imports OK.")
PYCHECK

# ---------------------------------------------------------------------------
# 6. Print next steps
# ---------------------------------------------------------------------------
echo ""
echo "============================================================"
echo "Setup complete.  Next steps:"
echo ""
echo "  1. Build your study spec (see hpc/examples/):"
echo "       cp hpc/examples/study_spec_sweep.yaml my_study.yaml"
echo "       # Edit my_study.yaml for your case"
echo ""
echo "  2. Generate configs and SLURM script:"
echo "       python hpc/study_builder.py my_study.yaml"
echo ""
echo "  3. Edit the generated modules.sh for your cluster:"
echo "       nano <output_dir>/modules.sh"
echo ""
echo "  4. Submit:"
echo "       sbatch <output_dir>/submit_array.sh"
echo ""
echo "  5. After jobs finish, aggregate results:"
echo "       python hpc/aggregate_results.py <output_dir>/manifest.csv"
echo "============================================================"
