#!/bin/bash
# =============================================================================
# hpc/setup_env.sh  --  Bootstrap the QuESt Planning Python environment on HPC
# =============================================================================
# Run this ONCE on the cluster login node before submitting any jobs.
#
# Usage:
#   bash hpc/setup_env.sh [--repo-path /absolute/path/to/repo]
#
# If --repo-path is omitted, the script uses the directory one level above
# this hpc/ folder (i.e. the repo root), which is correct when you run it as:
#   bash hpc/setup_env.sh
# from inside the repo.
#
# What this script does:
#   1. Locates conda/micromamba — checks PATH first, then common install
#      locations, then tries to source the conda shell hook so that
#      'conda activate' works reliably inside a non-interactive script.
#   2. Creates a conda environment named 'quest_planning' with Python 3.11.
#   3. Installs all Python dependencies from requirements.txt.
#   4. Installs the quest_planning package in editable mode.
#   5. Verifies that the key imports work (no solver required).
#
# Prerequisites:
#   - conda or miniconda/micromamba installed on the login node.
#     If it is not on PATH, load its module first, e.g.:
#       module load anaconda3
#     or provide CONDA_ROOT below.
#   - Gurobi installed separately (via cluster module or site license).
#     The Python gurobipy package is installed here but Gurobi itself must
#     be available at job runtime via modules.sh.
#
# After running this script, edit hpc/modules.sh (generated by study_builder.py)
# to activate this environment in each SLURM job.
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Parse arguments
# ---------------------------------------------------------------------------
# Default: parent of the hpc/ directory (the repo root).
REPO_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --repo-path)
            REPO_PATH="$2"
            shift 2
            ;;
        *)
            echo "ERROR: Unknown argument: $1" >&2
            echo "Usage: bash hpc/setup_env.sh [--repo-path /path/to/repo]" >&2
            exit 1
            ;;
    esac
done

# Validate repo path
if [[ ! -d "$REPO_PATH" ]]; then
    echo "ERROR: Repository path does not exist: $REPO_PATH" >&2
    echo "       Pass the correct path with --repo-path, e.g.:" >&2
    echo "         bash hpc/setup_env.sh --repo-path /projects" >&2
    exit 1
fi

if [[ ! -f "$REPO_PATH/requirements.txt" ]]; then
    echo "ERROR: requirements.txt not found under $REPO_PATH" >&2
    echo "       Make sure --repo-path points to the QuESt Planning repo root." >&2
    exit 1
fi

ENV_NAME="quest_planning"
PYTHON_VERSION="3.11"

echo "============================================================"
echo "QuESt Planning HPC Environment Setup"
echo "Repository : $REPO_PATH"
echo "Conda env  : $ENV_NAME (Python $PYTHON_VERSION)"
echo "============================================================"

# ---------------------------------------------------------------------------
# 1. Locate conda / micromamba
#
# Strategy (in order):
#   a) micromamba on PATH
#   b) conda on PATH
#   c) conda binary at common install locations (covers the case where conda
#      is installed but its shell hook has not been sourced yet)
#   d) Fail with a clear, actionable error message
# ---------------------------------------------------------------------------

CONDA_CMD=""
CONDA_ROOT=""

_try_conda_at() {
    # Try the conda binary at a given prefix; set CONDA_CMD and CONDA_ROOT
    # if it is usable.
    local prefix="$1"
    local binary="${prefix}/bin/conda"
    if [[ -x "$binary" ]]; then
        CONDA_CMD="$binary"
        CONDA_ROOT="$prefix"
        return 0
    fi
    return 1
}

if command -v micromamba &>/dev/null; then
    CONDA_CMD="micromamba"
    CONDA_ROOT="$(micromamba info --base 2>/dev/null || true)"
elif command -v conda &>/dev/null; then
    CONDA_CMD="conda"
    CONDA_ROOT="$(conda info --base 2>/dev/null || true)"
else
    # Conda is not on PATH — search common install locations
    echo "conda/micromamba not found on PATH; searching common locations ..."
    for _prefix in \
        "/opt/conda" \
        "$HOME/miniconda3" \
        "$HOME/anaconda3" \
        "$HOME/miniforge3" \
        "$HOME/mambaforge" \
        "/usr/local/anaconda3" \
        "/usr/local/miniconda3" \
        "/apps/anaconda3" \
        "/apps/miniconda3" \
        "/sw/anaconda3" \
        "/sw/miniconda3"
    do
        if _try_conda_at "$_prefix"; then
            echo "  Found conda at: ${CONDA_CMD}"
            break
        fi
    done

    if [[ -z "$CONDA_CMD" ]]; then
        echo ""
        echo "ERROR: conda/micromamba could not be found." >&2
        echo "" >&2
        echo "  Options:" >&2
        echo "    1. Load the anaconda/conda module for your cluster first:" >&2
        echo "         module load anaconda3" >&2
        echo "       Then re-run this script." >&2
        echo "" >&2
        echo "    2. Or provide the conda root path directly by editing" >&2
        echo "       CONDA_ROOT near the top of this script." >&2
        echo "" >&2
        echo "    3. Or install Miniconda manually:" >&2
        echo "         wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh" >&2
        echo "         bash Miniconda3-latest-Linux-x86_64.sh -b -p \$HOME/miniconda3" >&2
        echo "         source \$HOME/miniconda3/etc/profile.d/conda.sh" >&2
        echo "       Then re-run this script." >&2
        exit 1
    fi
fi

echo "Using: $CONDA_CMD"
[[ -n "$CONDA_ROOT" ]] && echo "Root  : $CONDA_ROOT"

# ---------------------------------------------------------------------------
# 2. Source the conda shell hook so 'conda activate' works in this script
#
# When running as 'bash script.sh' (non-interactive), the conda shell
# functions are not automatically available.  We source the hook explicitly.
# ---------------------------------------------------------------------------
if [[ "$CONDA_CMD" == "micromamba" ]]; then
    eval "$(micromamba shell hook --shell bash)"
else
    # Determine conda root if not already set
    if [[ -z "$CONDA_ROOT" ]]; then
        CONDA_ROOT="$("$CONDA_CMD" info --base)"
    fi
    CONDA_HOOK="${CONDA_ROOT}/etc/profile.d/conda.sh"
    if [[ -f "$CONDA_HOOK" ]]; then
        # shellcheck disable=SC1090
        source "$CONDA_HOOK"
        # After sourcing, 'conda' is now a shell function; use it directly.
        CONDA_CMD="conda"
    else
        echo "WARNING: conda shell hook not found at $CONDA_HOOK" >&2
        echo "         'conda activate' may not work; falling back to direct binary." >&2
    fi
fi

# ---------------------------------------------------------------------------
# 3. Create environment (skip if already exists)
# ---------------------------------------------------------------------------
if $CONDA_CMD env list | grep -qE "^${ENV_NAME}[[:space:]]"; then
    echo "Environment '$ENV_NAME' already exists — skipping creation."
else
    echo "Creating conda environment '$ENV_NAME' with Python $PYTHON_VERSION ..."
    $CONDA_CMD create -n "$ENV_NAME" python="$PYTHON_VERSION" -y
fi

# ---------------------------------------------------------------------------
# 4. Activate and install dependencies
# ---------------------------------------------------------------------------
echo "Activating environment '$ENV_NAME' ..."
if [[ "$CONDA_CMD" == "micromamba" ]]; then
    micromamba activate "$ENV_NAME"
else
    conda activate "$ENV_NAME"
fi

echo "Installing dependencies from requirements.txt ..."
pip install --upgrade pip --quiet
pip install -r "${REPO_PATH}/requirements.txt"

# ---------------------------------------------------------------------------
# 5. Install the quest_planning package in editable mode
# ---------------------------------------------------------------------------
echo "Installing quest_planning package (editable) ..."
pip install -e "${REPO_PATH}" --quiet

# ---------------------------------------------------------------------------
# 6. Quick import verification (no solver required)
# ---------------------------------------------------------------------------
echo ""
echo "Verifying key imports ..."
python - <<'PYCHECK'
import sys
failures = []

checks = [
    ("yaml",                              "PyYAML"),
    ("pandas",                            "pandas"),
    ("numpy",                             "numpy"),
    ("pyomo.environ",                     "Pyomo"),
    ("sklearn.cluster",                   "scikit-learn"),
    ("quest_planning.explan_simulation",  "quest_planning"),
    ("quest_planning.explan.explan_data_handler",    "ExplanDataHandler"),
    ("quest_planning.explan.explan_optimizer",       "ExplanOptimizer"),
    ("quest_planning.explan.explan_results_viewer",  "ExplanResultsViewer"),
]

for module, label in checks:
    try:
        __import__(module)
        print(f"  OK  {label} ({module})")
    except ImportError as e:
        print(f"  FAIL {label} ({module}): {e}")
        failures.append(module)

if failures:
    print(f"\nFAILED imports: {failures}")
    sys.exit(1)
else:
    print("\nAll imports OK.")
PYCHECK

# ---------------------------------------------------------------------------
# 7. Print next steps
# ---------------------------------------------------------------------------
echo ""
echo "============================================================"
echo "Setup complete.  Next steps:"
echo ""
echo "  1. Copy and edit a study spec from the examples:"
echo "       cp ${REPO_PATH}/hpc/examples/study_spec_sweep.yaml my_study.yaml"
echo "       # Set output_dir, gurobi_license_file, partition, account, etc."
echo ""
echo "  2. Generate configs and SLURM job array script:"
echo "       python ${REPO_PATH}/hpc/study_builder.py my_study.yaml"
echo ""
echo "  3. Edit the generated modules.sh for your cluster:"
echo "       nano <output_dir>/modules.sh"
echo ""
echo "  4. Submit the job array:"
echo "       sbatch <output_dir>/submit_array.sh"
echo ""
echo "  5. After all jobs finish, aggregate results:"
echo "       python ${REPO_PATH}/hpc/aggregate_results.py <output_dir>/manifest.csv"
echo "============================================================"
