# ***QuESt Planning Configuration File***

#********************Data Folder********************
data_folder: 'rts_csv_data_zonal'

#********************Scenario Configuration********************
scenario: RTS_GMLC_1_Base
system: RTS_GMLC
tx_model: dc
trans_expansion: False
load_growth: 1.5
load_forecast: system_wide
es_cost: Base
ldes_switch: False

#********************Time Horizon********************
start_year: 2024
end_year: 2024
#year_gap: 16
years:
  - 2024
#  - 2025
#  - 2026
#  - 2027
#  - 2028
#  - 2029
#  - 2030
#  - 2031
#  - 2032
#  - 2033
#  - 2034
#  - 2035
#  - 2036
#  - 2037
#  - 2038
#  - 2039
#  - 2040
  
#********************Economic Parameters********************
discount_rate: 5
base_curr_year: 2021
end_effects: 10
voll: 100000
tax_credit_end_year: 2032

#********************Energy Storage Options********************
soc_max: 80
soc_min: 20
ini_level: 50
es_lifetime_extension: 50

#********************Modeling Options:********************
block_selection: Full_Year #Full_Year #seasonal_blocks or Repr_Weeks
reserves_option: True
tax_credits_option: False
es_lifetime_cost_option: True
large_load_option: False
rps_policy: False #True if you want to enforce RPS policy
co2_policy: False
co2_intensity_policy: False
mva_base: 100

#********************Reliability Options:********************
evaluate_reliability: True #True if you want to evaluate reliability indices at the end of the planning optimization and export reliability data and plots
run_as_MILP: False #If True, investment decision capacities are fixed. CandCap column in gen.csv is the candidate capacity
enforce_reliability_constraint: False #True to enforce reliability constraints. Can only be True if run_as_MILP is True and evaluate_reliability is True
maxLoadLossHours: 20 #Only active if enforce_reliability_constraint is True

#********************Candidate Technologies - NOT ACTIVE********************

#********************Limit by Buses********************
limit_by_buses: null
  #- bus_num: 1
   # solar: 1000
   # wind: 0
   # storage: 750

#********************System-wide resource limits********************
system_wide_wind_max: 10000000
system_wide_solar_max: 150000000
system_wide_gas_max: 10000000
system_wide_tx_expansion_max: 3000

#********************Reserves Parameters********************
prm: 20
reg_res_req: 1
spin_res_req: 3
flex_res_w_req: 10
flex_res_s_req: 4

#********************Custom Retirements********************
custom_retirement: False
ng_retirement_year: None
coal_retirement_year: None
nuclear_retirement_year: None
oil_retirement_year: None

#********************Solver********************
solver: gurobi

#********************Plotting Options********************
stacked_bar_by_bus: False
policy_plot_option: False





